animal = input('Diga um nome de animal__')
fruta = input('Diga uma fruta__')
Pais = input('Diga um nome de um Pais__')
objeto = input('Diga o nome de um objeto__')
brinquedo = input('Escreve um nome de um brinquedo__')
numero = input('Digite um numero qualquer__')
adjetivo = input('Diga um adjetivo que seja ruim__')

print()
print("O(A) Fantastico(a) Mundo de " + animal + ".")
print()
print("Era uma vez um " + animal + "," " ele(a) comia todos os dias " + numero + " cabecas de " + fruta + ".")
print("Porem toda vez que comia ele pensava no(a) " + Pais + ".")
print("Com raiva sentia vontade de sair dentro do(a) " + objeto + ".")
print("Quando estava fora do(a) " + objeto + " jogava " + brinquedo + " " + numero + " vezes por dia" ".")
print("Voce leu essa historia e nao tem nada haver com o(a) " + animal + " nao eh mesmo? ")
print("Perdeu seu tempo seu(sua) " + adjetivo + " kkkk ")
